using System.Reflection;

[assembly: AssemblyTitle("LiteFramework.Editor")]
[assembly: AssemblyDescription("Generated by PackageGenerator.")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
