#if UNITY_EDITOR
using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using LiteFramework.Core.Utility;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

public class VContainerRegisterBuildProcessor : IPreprocessBuildWithReport
{
    public int callbackOrder => 0;

    public void OnPreprocessBuild(BuildReport report)
    {
        GenerateRegisterClass();
    }

    private const string OutputPath = "Assets/[LiteFramework]Generated/VContainerRegister.g.cs";
    private const string NamespaceName = "LiteFramework.Code.Generated";
    private const string TargetClassName = "VContainerRegister";

    [MenuItem("LiteFramework/VContainer/Generate AutoRegister Code")]
    public static void GenerateRegisterClass()
    {
        Debug.Log("🔧 [VContainer] 正在生成 VContainerRegister 初始化类...");

        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by VContainerRegisterBuildProcessor");
        sb.AppendLine("using LiteFramework.Core.Utility;");
        sb.AppendLine("using VContainer;");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine("namespace " + NamespaceName);
        sb.AppendLine("{");
        sb.AppendLine($"    public static class {TargetClassName}");
        sb.AppendLine("    {");
        sb.AppendLine("        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]");
        sb.AppendLine("        static void Register()");
        sb.AppendLine("        {");

        var assemblies = AppDomain.CurrentDomain.GetAssemblies()
            .Where(a => a.FullName.StartsWith("Assembly-CSharp"))
            .ToArray();

        foreach (var assembly in assemblies)
        {
            foreach (var type in assembly.GetTypes())
            {
                var attr = type.GetCustomAttribute<AutoRegisterAttribute>();
                if (attr != null && !type.IsAbstract)
                {
                    var typeName = type.FullName.Replace("+", ".");
                    sb.AppendLine($"            VContainerAutoRegister.registerDict.Add(typeof({typeName}), Lifetime.{attr.Lifetime});");
                }
            }
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        Directory.CreateDirectory(Path.GetDirectoryName(OutputPath)!);
        File.WriteAllText(OutputPath, sb.ToString());
        AssetDatabase.Refresh();

        Debug.Log($"✅ [VContainer] 注册类已生成: {OutputPath}");
    }
}
#endif
